<a href="https://colab.research.google.com/github/GDharan10/Project9_HorseRacePrediction/blob/main/HorseRacePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Libraries**

In [3]:
import pandas as pd
import glob
import os

In [5]:
# For displaying all of the columns in dataframes
pd.set_option('display.max_columns', None)

# **Data collection**

In [ ]:
directory = '/content/drive/MyDrive/DTM15/Dataset/HorseRacePrediction/Horse'

# List all CSV files in the directory
all_files = glob.glob(os.path.join(directory, '*.csv'))

# Initialize lists to hold dataframes
horses_dfs = []
races_dfs = []

# Process each file
for file in all_files:
    # Extract the base filename (without directory)
    base = os.path.basename(file).lower()

    # Split filename to check format (horses_YYYY.csv or races_YYYY.csv)
    if base.startswith('horses_') or base.startswith('races_'):
        # Determine category ('horses' or 'races')
        category = base.split('_')[0].lower()

        # Read the file into a dataframe
        df = pd.read_csv(file)

        # Extract the year from the filename and add as a column
        year = base.split('_')[1].split('.')[0]
        df['Year'] = year

        # Append the dataframe to the appropriate list based on category
        if category == 'horses':
            horses_dfs.append(df)
        elif category == 'races':
            races_dfs.append(df)

# Concatenate all dataframes in each list into a single dataframe
horses_df = pd.concat(horses_dfs, ignore_index=True)
races_df = pd.concat(races_dfs, ignore_index=True)

In [10]:
horses_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4107315 entries, 0 to 4107314
Data columns (total 29 columns):
 #   Column        Dtype
---  ------        -----
 0   rid           int64
 1   horseName     object
 2   age           float64
 3   saddle        float64
 4   decimalPrice  float64
 5   isFav         int64
 6   trainerName   object
 7   jockeyName    object
 8   position      int64
 9   positionL     object
 10  dist          object
 11  weightSt      int64
 12  weightLb      int64
 13  overWeight    float64
 14  outHandicap   float64
 15  headGear      object
 16  RPR           float64
 17  TR            float64
 18  OR            float64
 19  father        object
 20  mother        object
 21  gfather       object
 22  runners       int64
 23  margin        float64
 24  weight        int64
 25  res_win       float64
 26  res_place     float64
 27  Year          object
 28  price         object
dtypes: float64(11), int64(7), object(11)
memory usage: 908.8+ MB

In [7]:
horses_df.head()

,rid,horseName,age,saddle,decimalPrice,isFav,trainerName,jockeyName,position,positionL,dist,weightSt,weightLb,overWeight,outHandicap,headGear,RPR,TR,OR,father,mother,gfather,runners,margin,weight,res_win,res_place,Year,price
0,272760,Tetlami,4.0,3.0,0.200000,1,Nicky Henderson,Barry Geraghty,1,NaN,NaN,11,2,NaN,NaN,NaN,112.0,NaN,NaN,Daylami,Tetou,Peintre Celebre,15,1.208562,70,1.0,1.0,2010,NaN
1,272760,Romulus D'Artaix,4.0,14.0,0.142857,0,Alan King,Robert Thornton,2,4,NaN,10,12,NaN,NaN,NaN,99.0,NaN,NaN,Sassanian,Kadisha,Always Fair,15,1.208562,68,0.0,1.0,2010,NaN
2,272760,Marleno,4.0,9.0,0.024390,0,Milton Harris,Warren Marston,3,nk,4.25,10,12,NaN,NaN,NaN,99.0,NaN,NaN,Lecroix,Mondalita,Alkalde,15,1.208562,68,0.0,1.0,2010,NaN
3,272760,My Brother Sylvest,4.0,10.0,0.076923,0,John Flint,Rhys Flint,4,5,9.25,10,9,NaN,NaN,NaN,93.0,NaN,NaN,Bach,Senna Da Silva,Prince Of Birds,15,1.208562,67,0.0,0.0,2010,NaN
4,272760,Karasenir,4.0,8.0,0.076923,0,Philip Hobbs,Richard Johnson,5,.75,10.0,10,12,NaN,NaN,NaN,92.0,NaN,NaN,Sendawar,Karasta,Lake Coniston,15,1.208562,68,0.0,0.0,2010,NaN

In [11]:
races_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396572 entries, 0 to 396571
Data columns (total 20 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   rid          396572 non-null  int64
 1   course       396572 non-null  object
 2   time         396572 non-null  object
 3   date         396572 non-null  object
 4   title        396571 non-null  object
 5   rclass       243580 non-null  object
 6   band         165263 non-null  object
 7   ages         383518 non-null  object
 8   distance     396572 non-null  object
 9   condition    396524 non-null  object
 10  hurdles      121619 non-null  object
 11  prizes       396572 non-null  object
 12  winningTime  396572 non-null  float64
 13  prize        376864 non-null  float64
 14  metric       396572 non-null  float64
 15  countryCode  396572 non-null  object
 16  ncond        396572 non-null  object
 17  class        396572 non-null  int64
 18  Year         396572 non-null  object
 19  currency     9281 non-null    object
dtypes: float64(3), int64(2), object(15)
memory usage: 60.5+ MB

In [9]:
races_df.head()

,rid,course,time,date,title,rclass,band,ages,distance,condition,hurdles,prizes,winningTime,prize,metric,countryCode,ncond,class,Year,currency
0,272760,Cheltenham,03:50,10/01/01,"EBF ""High Sheriff of Gloucestershire's"" ""Junio...",Class 1,NaN,4yo,1m6f,Soft,NaN,"[10115.0, 3787.6, 1892.1, 945.2]",222.70,16740.0,2815.0,GB,5,1,2010,NaN
1,280996,Cheltenham,01:40,10/01/01,Dipper Novices' Chase Grade 2,Class 1,NaN,5yo+,2m5f,Soft,17 fences,"[18243.2, 6844.8]",357.30,25088.0,4223.0,GB,5,1,2010,NaN
2,286408,Southwell (AW),01:35,10/01/01,Betdaq The Betting Exchange Handicap,Class 5,0-75,4yo+,1m6f,Standard To Slow,NaN,"[2331.36, 693.72, 346.68, 173.16]",195.35,3545.0,2815.0,GB,13,5,2010,NaN
3,288208,Tramore (IRE),02:30,10/01/01,New Years Day at Tramore Racecourse 6YO Maiden...,NaN,NaN,6yo,2m,Heavy,10 hurdles,"[5182.5, 1207.5, 532.5, 307.5]",268.00,7230.0,3218.0,IE,9,0,2010,NaN
4,297757,Southwell (AW),12:25,10/01/01,Happy New Year Apprentice Median Auction Maide...,Class 6,NaN,4-6yo,1m3f,Standard To Slow,NaN,"[1774.24, 523.9, 262.08]",154.92,2560.0,2212.0,GB,13,6,2010,NaN